### ISSUE TITLE
Is there any code added?

### ISSUE THREAD

**Issue by SteveOverSea** [antalsz/obsidian-noisy-editorsuggest#1]
It seems like this is just the sample-plugin code. Am I blind, or is there no code added that would show the noisy-editorsuggest?

**Comment by antalsz** [comment]
You're right, I never pushed my testing code!  I've done that now (910ace01fb01c9881ac23bc395893e9aedf03d4d) :-)

Also, though, how on earth did you find my test plugin repository?  I never expected any interaction here!

**Comment by SteveOverSea** [comment]
I was looking for repos using the EditorSuggest from the Obsidian API since I wanted to see some examples for it. I need to implement one in a [folder link plugin](https://github.com/SteveOverSea/obsidian-folder-links) I am currently working on.

Your repo looked very suitable for a first starting point on how to use it. And thanks for pushing the code now, I think it still could be a helpful reference. 😁

In the end I found some useful snippets in the [Obsidian Boost Link Suggestions](https://github.com/jglev/obsidian-boost-link-suggestions) repo
